### ISSUE TITLE
公开mi3dor2数据集吗

### ISSUE THREAD

**Issue by MrLogic1** [tianbao-li/HUCN#1]
mi3dor2数据集下载地址能否提供一下或者说怎么才能得到mi3dor2数据集的使用权限呢

**Comment by tianbao-li** [comment]
你好，你留个邮箱，我先发你一份MI3DOR-2的数据集，等我们整理后会公布在本GitHub项目里。

**Comment by Guan-yunchang** [comment]
你好，MI3DOR与MI3DOR-2数据集现在有下载地址了吗，怎么下载数据集

**Comment by GITHUB520520** [comment]
您好，现在有MI3DOR1与2数据集的下载地址吗
